//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gorevler()
        {
            this.gorevDetay = new HashSet<gorevDetay>();
        }
    
        public int id { get; set; }
        public Nullable<int> gorevVeren { get; set; }
        public Nullable<int> gorevAlan { get; set; }
        public Nullable<int> mudurluk { get; set; }
        public Nullable<int> birim { get; set; }
        public Nullable<int> baslik { get; set; }
        public Nullable<int> islem { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> islemDurumu { get; set; }
    
        public virtual birimler birimler { get; set; }
        public virtual elemanlar elemanlar { get; set; }
        public virtual elemanlar elemanlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorevDetay> gorevDetay { get; set; }
        public virtual islemBasliklari islemBasliklari { get; set; }
        public virtual islemDurmu islemDurmu { get; set; }
        public virtual islemler islemler { get; set; }
        public virtual mudurlukler mudurlukler { get; set; }
    }
}
